export const BaseColaboradores = [
	{
		id: '1',
		nombre: 'Juan Soto',
		correo: 'juans@colaborador.com',
		edad: '23',
		cargo: 'Desarrollador FrontEnd',
		telefono: '99887766',
	},
	{
		id: '2',
		nombre: 'Lucas Pailamilla',
		correo: 'lucasp@colaborador.com',
		edad: '31',
		cargo: 'Desarrollador Backend',
		telefono: '88779955',
	},
	{
		id: '3',
		nombre: 'Diego Riquelme',
		correo: 'diegor@colaborador.com',
		edad: '28',
		cargo: 'Ingeniero DevOps',
		telefono: '99226644',
	},
	{
		id: '4',
		nombre: 'Ana López',
		correo: 'anal@colaborador.com',
		edad: '26',
		cargo: 'Diseñadora UX/UI',
		telefono: '66554433',
	},
	{
		id: '5',
		nombre: 'Carlos Fernández',
		correo: 'carlosf@colaborador.com',
		edad: '29',
		cargo: 'Analista de Datos',
		telefono: '77665544',
	},
	{
		id: '6',
		nombre: 'Laura González',
		correo: 'laurag@colaborador.com',
		edad: '35',
		cargo: 'Gerente de Proyectos',
		telefono: '55443322',
	},
	{
		id: '7',
		nombre: 'Sofía Rodríguez',
		correo: 'sofiar@colaborador.com',
		edad: '27',
		cargo: 'Tester de Software',
		telefono: '66778899',
	},
	{
		id: '8',
		nombre: 'Martín Díaz',
		correo: 'martind@colaborador.com',
		edad: '32',
		cargo: 'Arquitecto de Software',
		telefono: '88990011',
	},
	{
		id: '9',
		nombre: 'Elena Martínez',
		correo: 'elenam@colaborador.com',
		edad: '30',
		cargo: 'Especialista en Seguridad',
		telefono: '77889900',
	},
	{
		id: '10',
		nombre: 'Francisco Silva',
		correo: 'franciscos@colaborador.com',
		edad: '25',
		cargo: 'Scrum Master',
		telefono: '99001122',
	},
	{
		id: '11',
		nombre: 'Valeria Pérez',
		correo: 'valeriap@colaborador.com',
		edad: '28',
		cargo: 'Analista de Negocios',
		telefono: '66552211',
	},
	{
		id: '12',
		nombre: 'Roberto Gómez',
		correo: 'robertog@colaborador.com',
		edad: '34',
		cargo: 'Product Manager',
		telefono: '77887766',
	},
	{
		id: '13',
		nombre: 'María Torres',
		correo: 'mariat@colaborador.com',
		edad: '29',
		cargo: 'Desarrolladora FullStack',
		telefono: '55446688',
	},
	{
		id: '14',
		nombre: 'Luisa Ramírez',
		correo: 'luisar@colaborador.com',
		edad: '33',
		cargo: 'Especialista en QA',
		telefono: '66771122',
	},
	{
		id: '15',
		nombre: 'Javier Núñez',
		correo: 'javiern@colaborador.com',
		edad: '27',
		cargo: 'Analista de Sistemas',
		telefono: '99004455',
	},
	{
		id: '16',
		nombre: 'Paola Herrera',
		correo: 'paolah@colaborador.com',
		edad: '31',
		cargo: 'Diseñadora Gráfica',
		telefono: '88992233',
	},
	{
		id: '17',
		nombre: 'Ricardo Salazar',
		correo: 'ricardos@colaborador.com',
		edad: '26',
		cargo: 'Desarrollador Mobile',
		telefono: '66553311',
	},
	{
		id: '18',
		nombre: 'Catalina Muñoz',
		correo: 'catalinam@colaborador.com',
		edad: '30',
		cargo: 'Especialista en Redes',
		telefono: '77886655',
	},
	{
		id: '19',
		nombre: 'Felipe Rojas',
		correo: 'feliper@colaborador.com',
		edad: '29',
		cargo: 'Analista de Seguridad',
		telefono: '55449966',
	},
	{
		id: '20',
		nombre: 'Camila Castro',
		correo: 'camilac@colaborador.com',
		edad: '28',
		cargo: 'Ingeniera de Software',
		telefono: '66775544',
	},
];
